### ISSUE TITLE
merge with grails console

### ISSUE THREAD

**Issue by donalmurtagh** [dmahapatro/grails-actuator-ui#1]
in some sense both plugins are used to inspect a running app, so it might be worth combining their powers.

**Comment by dmahapatro** [comment]
Right now I am trying to link the console plugin from the actuator dashboard. The plugin still has to be added as a dependency in the app which uses the actuator ui plugin. This way end user has full control over the console plugin. @donalmurtagh

**Comment by dmahapatro** [comment]
[Done](https://github.com/dmahapatro/grails-actuator-ui/commit/a1b10ee59d11b2b3d7f2936838603b5c77c686d9). Will be available with v0.2. Thank you for the feedback.
