### ISSUE TITLE
More Info does nothing

### ISSUE THREAD

**Issue by artemik** [dmahapatro/grails-actuator-ui#10]
Plugin: 1.1
Grails: 3.2.1.

In the dashboard, clicking `More Info` buttons doesn't do anything. Is it just that there is nothing implemented yet or it's my misconfiguration (or a bug)? Please, add this info in the documentation also.

**Comment by dmahapatro** [comment]
@artemik `More Info` is nothing implemented yet. Moreover, I did not find anything crucial to be added as part of more info. Will try to rationalize it's use. Thank you for pointing that out.

**Comment by artemik** [comment]
Thanks.
